#!/usr/bin/env python3
"""Update pdf-inspector and its crates.io-generated Cargo lockfile."""

from __future__ import annotations

import argparse
import io
import json
import re
import subprocess
import sys
import tarfile
import urllib.request
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
PACKAGE_PATH = Path(__file__).with_name("package.nix")
LOCK_PATH = Path(__file__).with_name("Cargo.lock")
SEMVER_RE = re.compile(r"(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)")
VERSION_RE = re.compile(r'(?m)^(\s*version = ")([^"]+)(";)$')
HASH_RE = re.compile(r'(?m)^(\s*hash = ")([^"]+)(";)$')


def run(command: list[str]) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(
        command,
        cwd=REPO_ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        sys.stderr.write(result.stdout)
        sys.stderr.write(result.stderr)
        raise RuntimeError(f"command failed: {' '.join(command)}")
    return result


def github_release(version: str | None) -> dict[str, Any]:
    suffix = f"tags/v{version}" if version else "latest"
    request = urllib.request.Request(
        f"https://api.github.com/repos/firecrawl/pdf-inspector/releases/{suffix}",
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": "cocofarm-update",
        },
    )
    with urllib.request.urlopen(request) as response:
        data = json.load(response)
    if not isinstance(data, dict):
        raise TypeError("GitHub returned a non-object release")
    return data


def stable_version(release: dict[str, Any]) -> str:
    tag = release.get("tag_name")
    if not isinstance(tag, str) or not tag.startswith("v"):
        raise RuntimeError(f"invalid release tag: {tag!r}")
    version = tag.removeprefix("v")
    if SEMVER_RE.fullmatch(version) is None:
        raise RuntimeError(f"release is not a stable semantic version: {tag!r}")
    if release.get("draft") is not False or release.get("prerelease") is not False:
        raise RuntimeError(f"release is not stable: {tag!r}")
    return version


def source_hash(version: str) -> str:
    url = f"https://github.com/firecrawl/pdf-inspector/archive/refs/tags/v{version}.tar.gz"
    result = run(["nix", "store", "prefetch-file", "--json", "--unpack", url])
    data = json.loads(result.stdout)
    value = data.get("hash") if isinstance(data, dict) else None
    if not isinstance(value, str) or not value.startswith("sha256-"):
        raise RuntimeError("nix store prefetch-file returned an invalid hash")
    return value


def crate_lock(version: str) -> bytes:
    request = urllib.request.Request(
        f"https://crates.io/api/v1/crates/pdf-inspector/{version}/download",
        headers={"User-Agent": "cocofarm-update"},
    )
    with urllib.request.urlopen(request) as response:
        archive = response.read()
    member_name = f"pdf-inspector-{version}/Cargo.lock"
    with tarfile.open(fileobj=io.BytesIO(archive), mode="r:gz") as crate:
        member = crate.extractfile(member_name)
        if member is None:
            raise RuntimeError(f"{member_name} missing from crates.io archive")
        lock = member.read()
    if not lock.startswith(b"# This file is automatically @generated by Cargo."):
        raise RuntimeError("crates.io archive contains an invalid Cargo.lock")
    return lock


def update(
    version: str,
    *,
    force: bool = False,
    package_path: Path = PACKAGE_PATH,
    lock_path: Path = LOCK_PATH,
) -> bool:
    original_package = package_path.read_text()
    original_lock = lock_path.read_bytes() if lock_path.exists() else None
    versions = VERSION_RE.findall(original_package)
    hashes = HASH_RE.findall(original_package)
    if len(versions) != 1 or len(hashes) != 1:
        raise RuntimeError("package.nix does not have one version and one source hash")
    if versions[0][1] == version and not force:
        return False

    try:
        new_hash = source_hash(version)
        contents = VERSION_RE.sub(rf"\g<1>{version}\g<3>", original_package, count=1)
        contents = HASH_RE.sub(rf"\g<1>{new_hash}\g<3>", contents, count=1)
        package_path.write_text(contents)
        lock_path.write_bytes(crate_lock(version))
    except BaseException:
        package_path.write_text(original_package)
        if original_lock is None:
            lock_path.unlink(missing_ok=True)
        else:
            lock_path.write_bytes(original_lock)
        raise
    return (
        package_path.read_text() != original_package
        or lock_path.read_bytes() != original_lock
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", help="stable release version; defaults to latest")
    parser.add_argument("--force", action="store_true", help="refresh current release")
    args = parser.parse_args()

    version = stable_version(github_release(args.version))
    changed = update(version, force=args.force)
    print(f"pdf-inspector {version}: {'updated' if changed else 'already current'}")


if __name__ == "__main__":
    main()
